[server]
maxUploadSize = 25

["secrets"]
openai_api_key = "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"
[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00FF00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
